/**
 * Error Code Definitions
 * Reference: AH1-15 §15.3, AH1-31 §31.2
 */

export const ErrorCodes = {
  // Channel Errors
  CHANNEL_PAYLOAD_INVALID: 'CHANNEL_PAYLOAD_INVALID',
  CHANNEL_DELIVERY_FAILED: 'CHANNEL_DELIVERY_FAILED',
  CHANNEL_UNSUPPORTED_ATTACHMENT: 'CHANNEL_UNSUPPORTED_ATTACHMENT',
  
  // Identity Errors
  IDENTITY_NOT_BOUND: 'IDENTITY_NOT_BOUND',
  IDENTITY_BINDING_CONFLICT: 'IDENTITY_BINDING_CONFLICT',
  
  // Policy Errors
  POLICY_DENIED: 'POLICY_DENIED',
  POLICY_SNAPSHOT_MISSING: 'POLICY_SNAPSHOT_MISSING',
  POLICY_HASH_MISMATCH: 'POLICY_HASH_MISMATCH',
  POLICY_SCOPE_INVALID: 'POLICY_SCOPE_INVALID',
  
  // Workflow Errors
  WORKFLOW_PLANNING_FAILED: 'WORKFLOW_PLANNING_FAILED',
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_INVALID_REQUEST: 'WORKFLOW_INVALID_REQUEST',
  WORKFLOW_CONCURRENT_LIMIT: 'WORKFLOW_CONCURRENT_LIMIT',
  
  // Stage Errors
  STAGE_TIMEOUT: 'STAGE_TIMEOUT',
  STAGE_EXECUTION_FAILED: 'STAGE_EXECUTION_FAILED',
  
  // Executor Errors
  EXECUTOR_UNAVAILABLE: 'EXECUTOR_UNAVAILABLE',
  EXECUTOR_TOOL_CHAIN_FAILED: 'EXECUTOR_TOOL_CHAIN_FAILED',
  EXECUTOR_TEST_FAILED: 'EXECUTOR_TEST_FAILED',
  EXECUTOR_TIMEOUT: 'EXECUTOR_TIMEOUT',
  
  // Retrieval Errors
  RETRIEVAL_DEGRADED: 'RETRIEVAL_DEGRADED',
  RETRIEVAL_TIMEOUT: 'RETRIEVAL_TIMEOUT',
  RETRIEVAL_PERMISSION_DENIED: 'RETRIEVAL_PERMISSION_DENIED',
  
  // Fact Errors
  FACT_CONFLICT: 'FACT_CONFLICT',
  FACT_WRITE_FAILED: 'FACT_WRITE_FAILED',
  
  // Artifact Errors
  ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',
  ARTIFACT_UPLOAD_FAILED: 'ARTIFACT_UPLOAD_FAILED',
  
  // Integration Errors
  INTEGRATION_LLM_UNAVAILABLE: 'INTEGRATION_LLM_UNAVAILABLE',
  INTEGRATION_LLM_ERROR: 'INTEGRATION_LLM_ERROR',
  INTEGRATION_ALL_PROVIDERS_DOWN: 'INTEGRATION_ALL_PROVIDERS_DOWN',
  INTEGRATION_HERMES_TIMEOUT: 'INTEGRATION_HERMES_TIMEOUT',
  INTEGRATION_HERMES_CONNECTION_FAILED: 'INTEGRATION_HERMES_CONNECTION_FAILED',
  
  // System Errors
  SYSTEM_CONFIGURATION_ERROR: 'SYSTEM_CONFIGURATION_ERROR',
  SYSTEM_DATABASE_ERROR: 'SYSTEM_DATABASE_ERROR',
  SYSTEM_RATE_LIMIT_EXCEEDED: 'SYSTEM_RATE_LIMIT_EXCEEDED',
  SYSTEM_API_VERSION_RETIRED: 'SYSTEM_API_VERSION_RETIRED',
  SYSTEM_API_VERSION_NOT_FOUND: 'SYSTEM_API_VERSION_NOT_FOUND'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

export interface ErrorDetail {
  code: ErrorCode;
  message: string;
  retryable: boolean;
  detail?: Record<string, unknown>;
  trace_id?: string;
  timestamp?: string;
  documentation_url?: string;
}
